[package]
name = "rquery-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = { version="0.4.41", features=["serde"]}
serde = { version="1.0.219", features=["derive"] }
serde_json = "1.0.140"
tokio = { version="1.46.1", features=["macros","test-util"] }